#!/bin/bash
# See Readme.md file for further information
# Tested with Fedora 31 Gnome
# Version 11/10/19

#
# Thanks to... Alexandru Catalin Petrini <alexandru.c.petrini@gmail.com>
# for the Shell extension functions used in this script.
# https://github.com/cyberalex4life/gnome-shell-extension-cl/blob/master/gnome-shell-extension-cl
#

# Get the Real Username
RUID=$(who | awk 'FNR == 1 {print $1}')

#############
# Functions #
#############

function get_enabled_extensions() {
    enabled_extensions=( $(gsettings get org.gnome.shell enabled-extensions | \
                               sed -e 's|^@as ||g' | tr -d "[",",","]","\'") )
}

function get_installed_extensions() {
    global_installed_extensions=( $(find "/usr/share/gnome-shell/extensions/" \
                                         -maxdepth 1 -type d -name "*@*" -exec \
                                         /usr/bin/basename {} \;) )
    local_installed_extensions=( $(find "$HOME/.local/share/gnome-shell/extensions/" \
                                        -maxdepth 1 -type d -name "*@*" -exec \
                                        /usr/bin/basename {} \;) )

    if [ ${#local_installed_extensions[@]} -gt ${#global_installed_extensions[@]} ]
    then
        installed_extensions=( ${local_installed_extensions[@]} )
        test_extensions=( ${global_installed_extensions[@]} )
    else
        installed_extensions=( ${global_installed_extensions[@]} )
        test_extensions=( ${local_installed_extensions[@]} )
    fi
    for test_extension in "${test_extensions[@]}"
    do
        test_extension_not_doubled=true
        for installed_extension in "${installed_extensions[@]}"
        do
            if [ "$test_extension" = "$installed_extension" ]
            then
                test_extension_not_doubled=false
                break
            fi
        done
        if  [ $test_extension_not_doubled = true ]
        then
            test_extension=( $test_extension )
            installed_extensions=( "${installed_extensions[@]}" "${test_extension[@]}" )
        fi
    done
    echo "${installed_extensions[@]}"
}

function check_extension_is_enabled() {
    extension_to_check=$1
    enabled_extensions=( $(gsettings get org.gnome.shell enabled-extensions | \
                               sed -e 's|^@as ||g' | tr -d "[",",","]","\'") )
    for enabled_extension in "${enabled_extensions[@]}"
    do
        if [ "$enabled_extension" = "$extension_to_check" ]
        then
            echo true
            return
        fi
    done
    echo false
}

function check_extension_in_all_extensions() {
    extension_to_check=$1
    installed_extensions=( $(get_installed_extensions) )
    for installed_extension in "${installed_extensions[@]}"
    do
        if [ "$installed_extension" = "$extension_to_check" ]
        then
            echo true
            return
        fi
    done
    echo false
}

function enable_extension() {
    extension_to_enable=("$@")
    if  [ "$(check_extension_in_all_extensions "$extension_to_enable")" = false ]
    then
        echo "'$extension_to_enable' is not installed."
        #continue
    fi
    if  [ "$(check_extension_is_enabled "$extension_to_enable")" = true ]
    then
        echo "'$extension_to_enable' is already enabled."
        continue
    fi
    gnome-extensions enable "$extension_to_enable"
    return
}

function install_extension() {
  extensionuuid=$1
  gnome-extensions install "$extensionuuid" --force
}

function download_extension() {
    link=$1
    echo
    echo "*** Downloading... $link ***"
    echo
    wget $link
    zipfile=$( echo ${link} | cut -d / -f 5- )
    extensionname=$(unzip -c $zipfile metadata.json | grep uuid | cut -d \" -f4)
    echo "*** Installing extension $zipfile ***"
    install_extension $zipfile
    echo "*** Enabling extension $extensionname ***"
    enable_extension $extensionname
    rm $zipfile
    #restart_shell
}

#Create the restart_shell function (WiP)
#Problematic in Wayland
function restart_shell() {
  #[[ $( pgrep gnome-shell ) ]] || return
  echo "Restarting GNOME Shell in 5 seconds..."
  sleep 5s
  busctl --user call org.gnome.Shell /org/gnome/Shell org.gnome.Shell Eval s 'Meta.restart("Restarting…")'
}

#OK let's start...

clear

#Name the computer
HOSTNAME=$(hostnamectl status | grep -w Static | cut -f 6- -d' ')
if [ $HOSTNAME = "localhost.localdomain" ];
then
  read -p "Hi $RUID, what do you want to call this PC? " compname
  hostnamectl set-hostname --pretty --static --transient "$compname"
  echo
  echo "Thanks, here are the details:"
  hostnamectl status
  echo
  sleep 5.0
fi

clear

#Update and Upgrade
echo "***********************************************"
echo "* Updating and upgrading your system first... *"
echo "***********************************************"
sudo dnf -y update --refresh
sleep 5.0
clear

#install the User Theme extensions
if  [ "$(check_extension_is_enabled "user-theme@gnome-shell-extensions.gcampax.github.com")" = false ]
then
  echo "******************************************"
  echo "* Installing the User Theme extension... *"
  echo "******************************************"
  download_extension https://extensions.gnome.org/extension-data/user-themegnome-shell-extensions.gcampax.github.com.v38.shell-extension.zip
  sleep 5.0
fi

#Setup dialog for the menu
INSTDIALOG=$(rpm -qa | grep dialog | cut -c -6)
if [ "$INSTDIALOG" = "dialog" ];
then
  continue
else
  echo "Installing dialog..."
  sudo dnf -y install dialog
  sleep 5.0
fi
# Run dialog
cmd=(dialog --title "Fedora 31 Extra's Installer" --separate-output --checklist "Choose only ONE optional theme & select the software you want to install:" 22 80 16)
  options=(
    #A "<---Category: Software Repositories--->" on
      1_repos " Install Flathub Repository" off
      2_repos " Install RPM Fusion Free & NonFree" off
      3_repos " Install Winepak Repository" off
    #B "<---Category: System--->" on
      1_system " Enable SMB" off
      2_system " Additional Fedora Wallpapers" off
    #C "<---Category: Social--->" on
      1_social " Slack Client" off
      2_social " Zoom Meeting Client" off
    #D "<---Category: Tweaks--->" on
      1_tweak " Gnome Tweak Tool" off
      2_tweak " Gnome Shell Extensions" off
      3_tweak " Microsoft Windows Style Decorations" off
    #E "<---Category: Media--->" on
      1_media " Google Desktop Player (Flatpak)" off
      2_media " VLC Player" off
      3_media " Media Codecs (requires RPM Fusion)" off
      4_media " Lollypop" off
      5_media " Plex Media Server" off
      6_media " Spotify" off
    #F "<---Category: Internet--->" on
      1_internet " Google Chrome Browser" off
    #G "<---Category: Video, Audio & Pic Editing--->" on
      1_edit " Kdenlive" off
      2_edit " Shotwell" off
	    3_edit " GIMP (Flatpak)" off
	    4_edit " OBS-Studio" off
	    5_edit " Audacity" off
    #H "<---Category: Themes--->" on
      1_themes " Papirus Icon Theme" off
      2_themes " Materia Theme" off
      3_themes " Flat-Remix Theme" off
    #I "<---Category: Utilities--->" on
      1_utility " Virtualbox" off
      2_utility " Etcher" off
      3_utility " Nano" off
      4_utility " qBitorrent" off
      5_utility " Neofetch" off
      6_utility " Atom" off
      7_utility " Clam AntiVirus" off
    #J "<---Category: Common Extensions--->" on
      1_extensions " MPIS indicator button" off
      2_extensions " OpenWeather" off
      3_extensions " Workspaces to Dock" off
      4_extensions " Caffeine" off
      5_extensions " Dash to Dock" off
      6_extensions " Coverflow Alt-Tab" off
      7_extensions " Removable Drive Menu" off
      8_extensions " GSConnect" off
      9_extensions " Transparent GNOME panel" off
    #K "<---Category: Gaming & Fun--->" on
      1_gaming " Steam (Flatpak)" off
      2_gaming " Lutris" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
  clear
    for choice in $choices
    do
      case $choice in
        # Section A ----------repos----------
          1_repos)
            #Install Flathub Repository (Software Repository)
            echo "************************************"
            echo "* Installing Flathub Repository... *"
            echo "************************************"
            sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
            sleep 5.0
            ;;
          2_repos)
            #Install RPM Packages
            echo "******************************************"
            echo "* Installing RPM package repositories... *"
            echo "******************************************"
            sudo dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
            sudo dnf -y install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
            sudo dnf -y update
            sleep 5.0
            ;;
          3_repos)
            #Install Winepak Repository
              echo "************************************"
              echo "* Installing Winepak Repository... *"
              echo "************************************"
              sudo flatpak remote-add --if-not-exists winepak https://dl.winepak.org/repo/winepak.flatpakrepo
              sleep 5.0
              ;;

        # Section B ----------system----------
          1_system)
            #SMB
              echo "*********************"
              echo "* Installing SMB... *"
              echo "*********************"
              sudo dnf -y install samba
              sudo systemctl enable smb nmb
              sudo systemctl start smb
              sudo systemctl start nmb
              sudo firewall-cmd --add-service=samba --permanent
              sudo firewall-cmd --reload
              sleep 5.0
              ;;
          2_system)
            #Wallpapers
              echo "**********************************************"
              echo "* Installing additional Fedora Wallpapers... *"
              echo "**********************************************"
              sudo dnf -y install f30-backgrounds-gnome
              sudo dnf -y install f30-backgrounds-extras-gnome
              sudo dnf -y install f29-backgrounds-gnome
              sudo dnf -y install f29-backgrounds-extras-gnome
              sudo dnf -y install f28-backgrounds-gnome
              sudo dnf -y install f28-backgrounds-extras-gnome
              sudo dnf -y install f27-backgrounds-gnome
              sudo dnf -y install f27-backgrounds-extras-gnome
              #sudo dnf -y install f26-backgrounds-gnome
              #sudo dnf -y install f26-backgrounds-extras-gnome
              #sudo dnf -y install f25-backgrounds-gnome
              #sudo dnf -y install f25-backgrounds-extras-gnome
              #sudo dnf -y install f24-backgrounds-gnome
              #sudo dnf -y install f24-backgrounds-extras-gnome
              #sudo dnf -y install f23-backgrounds-gnome
              #sudo dnf -y install f23-backgrounds-extras-gnome
              #sudo dnf -y install f22-backgrounds-gnome
              #sudo dnf -y install f22-backgrounds-extras-gnome
              #sudo dnf -y install f21-backgrounds-gnome
              #sudo dnf -y install f21-backgrounds-extras-gnome
              #now set some wallpapers
              gsettings set org.gnome.desktop.background picture-options 'zoom'
              gsettings set org.gnome.desktop.background picture-uri 'file:///usr/share/backgrounds/f30/extras/i-see-stars.jpg'
              gsettings set org.gnome.desktop.background primary-color '#000000000000'
              gsettings set org.gnome.desktop.background secondary-color '#000000000000'
              gsettings set org.gnome.desktop.screensaver picture-options 'zoom'
              gsettings set org.gnome.desktop.screensaver picture-uri 'file:///usr/share/backgrounds/f30/extras/fabric.jpg'
              gsettings set org.gnome.desktop.screensaver primary-color '#000000000000'
              gsettings set org.gnome.desktop.screensaver secondary-color '#000000000000'
              sleep 5.0
              ;;

        # Section C ----------social----------
          1_social)
            #Slack Client
              echo "*************************************"
              echo "* Installing Slack Client (flatpak)... *"
              echo "*************************************"
              #sudo flatpak -y install flathub com.slack.Slack
	      wget https://downloads.slack-edge.com/linux_releases/slack-4.1.1-0.1.fc21.x86_64.rpm
              sudo dnf -y localinstall slack-4.1.1-0.1.fc21.x86_64.rpm
              rm slack-4.1.1-0.1.fc21.x86_64.rpm
              sleep 5.0
              ;;
          2_social)
            #Zoom
              echo "********************************************"
              echo "* Installing Zoom Meeting Client (wget)... *"
              echo "********************************************"
              wget https://zoom.us/client/latest/zoom_x86_64.rpm
              sudo dnf -y localinstall zoom_x86_64.rpm
              rm -rf zoom_x86_64.rpm
              sleep 5.0
              ;;

        # Section D ----------tweak----------
          1_tweak)
            #Gnome tweak tool
              echo "**********************************"
              echo "* Installing Gnome Tweak Tool... *"
              echo "**********************************"
              sudo dnf -y install gnome-tweak-tool
              sleep 5.0
              ;;
          2_tweak)
            #Gnome Shell Integration
              echo "*****************************"
              echo "* Installing Chrome Gnome Shell... *"
              echo "*****************************"
              sudo dnf -y install chrome-gnome-shell
              sleep 10.0
              ;;
          3_tweak)
            #Windows decorations
              echo "**********************************"
              echo "* Setting up Windows decorations *"
              echo "**********************************"
              gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,maximize,close'
              sleep 10.0
              ;;

        # Section E ----------media----------
          1_media)
            #Google Desktop Player (Flatpak)
              echo "*************************************************"
              echo "* Installing Google Desktop Player (flatpak)... *"
              echo "*************************************************"
              sudo flatpak -y install flathub com.googleplaymusicdesktopplayer.GPMDP
              sleep 5.0
              ;;
          2_media)
            #VLC
              echo "******************"
              echo "* Install VLC... *"
              echo "******************"
              sudo dnf -y install vlc
              sleep 5.0
              ;;
          3_media)
            #Install Media Codecs
              echo "******************************"
              echo "* Installing Media Codecs... *"
              echo "******************************"
              sudo dnf -y install gstreamer-plugins-bad gstreamer-plugins-ugly lame faad2
              sudo dnf -y install ffmpeg ffmpeg-libs gstreamer-ffmpeg
              sudo dnf -y install libaacs libbdplus
              rpm -ivh http://rpm.livna.org/livna-release.rpm
              sleep 5.0
              sudo dnf -y update
              sudo dnf -y install libdvdcss
              sudo dnf -y install gstreamer1-libav.x86_64
              sleep 5.0
              ;;
          4_media)
            #Lollypop
              echo "***************************************"
              echo "* Installing Lollypop Music Player... *"
              echo "***************************************"
              sudo dnf -y install lollypop
              sleep 5.0
              echo "Removing Rhythmbox..."
              sudo dnf -y remove rhythmbox
              sleep 5.0
              ;;
          5_media)
            #Plex Media Server
              echo "***********************************"
              echo "* Installing Plex Media Server... *"
              echo "***********************************"
              wget https://downloads.plex.tv/plex-media-server-new/1.18.0.1913-e5cc93306/redhat/plexmediaserver-1.18.0.1913-e5cc93306.x86_64.rpm
              sudo dnf -y install plexmediaserver-1.18.0.1913-e5cc93306.x86_64.rpm
              #To allow access to the USB without modifying the fstab file do the following...
              echo "Configuring Plex Server to run under this user profile..."
              #Set the config file location
              CONFIG="/lib/systemd/system/plexmediaserver.service"
              #Use sed to set the new config values...
              function set_config(){
                sed -i.bak "s/^\($1\s*=\s*\).*\$/\1$2/" $CONFIG
              }
              source $CONFIG
              User=$RUID
              set_config User $User
              Group=$RUID
              set_config Group $Group
              #Change the ownership of Plex to the current user...
              sudo chown -R $RUID:$RUID /var/lib/plexmediaserver
              echo "Starting Plex Server Service..."
              sudo systemctl enable plexmediaserver.service
              sudo systemctl start plexmediaserver
              rm plexmediaserver-1.18.0.1913-e5cc93306.x86_64.rpm
              echo "-------------------------------------------------------------------------"
              echo "- Go to: http://127.0.0.1:32400/web in your Web Browser to configure... -"
              echo "-------------------------------------------------------------------------"
              echo
              sleep 5.0
              ;;
          6_media)
            #Spotify
              echo "*************************"
              echo "* Installing Spotify... *"
              echo "*************************"
              sudo dnf -y config-manager --add-repo=http://negativo17.org/repos/fedora-spotify.repo
              sudo dnf -y install spotify-client
              sleep 5.0
              ;;

        # Section F ----------internet----------
          1_internet)
            #Google Chrome Stable
              echo "************************"
              echo "* Installing Chrome... *"
              echo "************************"
              sudo dnf -y install fedora-workstation-repositories
              sudo dnf config-manager --set-enabled google-chrome
              sudo dnf -y install google-chrome-stable
              echo "Removing Firefox..."
              sleep 5.0
              sudo dnf -y remove firefox
              sleep 5.0
              ;;

        # Section G ----------edit(Video/Audio/Pic)----------
          1_edit)
            #Kdenlive
              echo "**************************"
              echo "* Installing Kdenlive... *"
              echo "**************************"
              sudo dnf -y install kdenlive.x86_64
              sudo dnf -y install breeze-icon-theme.noarch
              sudo dnf -y install vlc
              sleep 5.0
              ;;
          2_edit)
            #Shotwell
              echo "**************************"
              echo "* Installing Shotwell... *"
              echo "**************************"
              sudo dnf -y install shotwell
              sleep 5.0
              ;;
          3_edit)
            #GIMP (Flatpak)
              echo "********************************"
              echo "* Installing GIMP (flatpak)... *"
              echo "********************************"
              sudo flatpak -y install https://flathub.org/repo/appstream/org.gimp.GIMP.flatpakref
              sleep 5.0
              ;;
          4_edit)
            #OBS Studio
              echo "****************************"
              echo "* Installing OBS Studio... *"
              echo "****************************"
              sudo dnf -y install ffmpeg
              sudo dnf -y install obs-studio
              sleep 5.0
              ;;
          5_edit)
            #Audacity
              echo "**************************"
              echo "* Installing Audacity... *"
              echo "**************************"
              sudo dnf -y install audacity
              sleep 5.0
              ;;

        # Section H ----------themes----------
          1_themes)
            #Papirus Icon Theme
              echo "*******************************************"
              echo "* Installing Papirus Icon Theme (copr)... *"
              echo "*******************************************"
              sudo dnf -y copr enable dirkdavidis/papirus-icon-theme
              sudo dnf -y update
              sudo dnf -y install papirus-icon-theme
              echo "Setting the icon theme..."
              gsettings set org.gnome.desktop.interface icon-theme 'Papirus'
              sleep 5.0
              ;;
          2_themes)
            #Materia Theme
              echo "**************************************"
              echo "* Installing Materia Theme (copr)... *"
              echo "**************************************"
              sudo dnf -y copr enable tcg/themes
              sudo dnf -y install materia-theme
              echo "Setting the GTK theme..."
              # Set gsettings for the User
              gsettings set org.gnome.desktop.interface gtk-theme 'Materia-compact'
              gsettings set org.gnome.shell.extensions.user-theme name 'Materia-compact'
              sleep 5.0
              ;;
          3_themes)
            #Flat-Remix Theme
              echo "*****************************************"
              echo "* Installing Flat-Remix Theme (copr)... *"
              echo "*****************************************"
              sudo dnf -y copr enable daniruiz/flat-remix
              sudo dnf -y update
              sudo dnf -y install flat-remix
              sudo dnf -y install flat-remix-gtk
              #sudo dnf -y install flat-remix-gnome
              echo "Setting the theme..."
              # Set gsettings for the User
              gsettings set org.gnome.desktop.interface gtk-theme 'Flat-Remix-GTK-Darker'
              gsettings set org.gnome.desktop.interface icon-theme 'Flat-Remix'
              sleep 5.0
              ;;

        # Section I ----------utility----------
          1_utility)
            #Virtualbox
              echo "****************************"
              echo "* Installing Virtualbox... *"
              echo "****************************"
              sudo dnf -y install VirtualBox.x86_64
              sudo dnf -y install virtualbox-guest-additions-ogl
              sleep 5.0
              ;;
          2_utility)
            #Etcher ISO Creator
              echo "*******************************"
              echo "* Installing Etcher (wget)... *"
              echo "*******************************"
              sudo wget https://balena.io/etcher/static/etcher-rpm.repo -O /etc/yum.repos.d/etcher-rpm.repo
              sudo dnf -y update
              sudo dnf -y install balena-etcher-electron
              sleep 5.0
              ;;
          3_utility)
            #Nano
              echo "***************************"
              echo "* Installing Nano edit... *"
              echo "***************************"
              sudo dnf -y install nano
              sleep 5.0
              ;;
          4_utility)
            #qBitorrent
              echo "****************************"
              echo "* Installing qBitorrent... *"
              echo "****************************"
              sudo dnf -y install qbittorrent
              sleep 5.0
              ;;
          5_utility)
            #Neofetch
              echo "**************************"
              echo "* Installing Neofetch... *"
              echo "**************************"
              sudo dnf -y install neofetch
              neofetch
              sleep 5.0
              ;;
          6_utility)
            #Atom
              echo "*****************************"
              echo "* Installing Atom (wget)... *"
              echo "*****************************"
              wget https://atom.io/download/rpm -O atom.x86_64.rpm
              sudo dnf -y localinstall atom.x86_64.rpm
              rm atom.x86_64.rpm
              sleep 5.0
              ;;
          7_utility)
            #Clam AV
              echo "*************************"
              echo "* Installing Clam AV... *"
              echo "*************************"
              sudo dnf -y install clamtk clamav clamav-update
              freshclam
              sleep 5.0
              ;;

        # Section J ----------extensions----------
          1_extensions)
            #Mpris Indicator Button
              echo "*********************************************************"
              echo "* Installing Mpris Indicator Button extension (wget)... *"
              echo "*********************************************************"
              download_extension https://extensions.gnome.org/extension-data/mprisindicatorbuttonJasonLG1979.github.io.v9.shell-extension.zip
              sleep 5.0
              ;;
          2_extensions)
            #OpenWeather
              echo "**********************************************"
              echo "* Installing OpenWeather extension (wget)... *"
              echo "**********************************************"
              download_extension https://extensions.gnome.org/extension-data/openweather-extension@jenslody.de.v97.shell-extension.zip
              #Set extension settings
              gsettings set org.gnome.shell.extensions.openweather unit 'celsius'
              gsettings set org.gnome.shell.extensions.openweather wind-speed-unit 'kph'
              gsettings set org.gnome.shell.extensions.openweather pressure-unit 'kPa'
              gsettings set org.gnome.shell.extensions.openweather city '-27.4869732,153.2393435>Wellington Point, QLD, 4160, Australia >-1'
              sleep 5.0
              ;;
          3_extensions)
            #Workspaces to Dock
              echo "****************************************************"
              echo "* Installing Worksaces to Dock extension (wget)... *"
              echo "****************************************************"
              download_extension https://extensions.gnome.org/extension-data/workspaces-to-dockpassingthru67.gmail.com.v52.shell-extension.zip
              #tweak the extension to intellihide
              gsettings set org.gnome.shell.extensions.workspaces-to-dock intellihide false
              sleep 5.0
              ;;
          4_extensions)
            #Caffeine
              echo "*********************************"
              echo "* Installing Caffeine (wget)... *"
              echo "*********************************"
              download_extension https://extensions.gnome.org/extension-data/caffeinepatapon.info.v32.shell-extension.zip
              sleep 5.0
              ;;
          5_extensions)
            #Dash to Dock
              echo "***********************************************"
              echo "* Installing Dash to Dock extension (wget)... *"
              echo "***********************************************"
              download_extension https://extensions.gnome.org/extension-data/dash-to-dockmicxgx.gmail.com.v67.shell-extension.zip
              gsettings set org.gnome.shell.extensions.dash-to-dock dock-position 'BOTTOM'
              gsettings set org.gnome.shell.extensions.dash-to-dock show-apps-at-top true
              gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-shrink true
              gsettings set org.gnome.shell.extensions.dash-to-dock transparency-mode 'ADAPTIVE'
              sleep 5.0
              ;;
          6_extensions)
            #Coverflow Alt-Tab
              echo "******************************************"
              echo "* Installing Coverflow Alt-Tab (wget)... *"
              echo "******************************************"
              download_extension https://extensions.gnome.org/extension-data/CoverflowAltTabpalatis.blogspot.com.v38.shell-extension.zip
              sleep 5.0
              ;;
          7_extensions)
            #Removable Drive Menu
              echo "**************************************"
              echo "* Installing Removable Drive Menu... *"
              echo "**************************************"
              download_extension https://extensions.gnome.org/extension-data/drive-menu@gnome-shell-extensions.gcampax.github.com.v41.shell-extension.zip
              sleep 5.0
              ;;
          8_extensions)
            #GSConnect
              echo "***************************"
              echo "* Installing GSConnect... *"
              echo "***************************"
              download_extension https://extensions.gnome.org/extension-data/gsconnect@andyholmes.github.io.v26.shell-extension.zip
              sleep 5.0
              ;;
          9_extensions)
            #GSConnect
              echo "******************************"
              echo "* Transparent GNOME panel... *"
              echo "******************************"
              download_extension https://extensions.gnome.org/extension-data/transparent-gnome-panel%40ttomovcik.com.v1.shell-extension.zip
              sleep 5.0
              ;;

        # Section K ----------game----------
          1_gaming)
            #Steam
              echo "*********************************"
              echo "* Installing Steam (Flatpak)... *"
              echo "*********************************"
              sudo flatpak -y install flathub com.valvesoftware.Steam
              sleep 5.0
              ;;
          2_gaming)
            #Lutris
              echo "************************"
              echo "* Installing Lutris... *"
              echo "************************"
              sudo dnf config-manager --add-repo https://download.opensuse.org/repositories/home:strycore/Fedora_28/home:strycore.repo
              sudo dnf -y update
              sudo dnf -y install lutris
              sleep 5.0
              ;;
            esac
          done
sleep 5.0
clear
echo "*******************************************************************"
echo "* Please restart your system for the updates to take full effect! *"
echo "*******************************************************************"
#restart_shell
